"use client"

import React, { useState } from 'react'
import Card from '../../components/ui/Card'
import Button from '../../components/ui/Button'
import AddContentInput from '../../components/ui/AddContentInput'
import AddContentLoading from '../../components/ui/AddContentLoading'
import AddContentResults from '../../components/ui/AddContentResults'
import AddContentError from '../../components/ui/AddContentError'

export default function AddPage() {
  const [front, setFront] = useState('')
  const [back, setBack] = useState('')
  const [error, setError] = useState('')

  const [state, setState] = useState<'idle'|'loading'|'results'|'error'>('idle')
  const [items, setItems] = useState<Array<{front:string,back:string}>>([])

  function onGenerate(text: string) {
    setState('loading')
    // simulate API
    setTimeout(() => {
      if (text.includes('error')) {
        setState('error')
        return
      }
      const generated = [
        { front: text.slice(0,40) + '…', back: 'Summary or answer generated by AI.' },
        { front: text.slice(0,30) + ' (card 2)', back: 'Another generated card.' },
      ]
      setItems(generated)
      setState('results')
    }, 900)
  }

  function onSave(idx:number) {
    // placeholder: mark saved
    alert('Saved card: ' + items[idx].front)
  }


  return (
    <div className="max-w-3xl mx-auto">
      <Card className="p-6">
        <h1 className="text-lg font-medium text-text-primary">Add content / Generate cards</h1>

        <div className="mt-4">
          {state === 'idle' && <AddContentInput onGenerate={onGenerate} />}
          {state === 'loading' && <AddContentLoading />}
          {state === 'results' && <AddContentResults items={items} onSave={onSave} />}
          {state === 'error' && <AddContentError message="AI service failed. Try again." onRetry={() => setState('idle')} />}
        </div>

        <div className="mt-6 flex justify-end">
          <Button variant="ghost" onClick={() => { setState('idle'); setItems([]) }}>Reset</Button>
        </div>
      </Card>
    </div>
  )
}
